apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    github.com/project-slug: hill-giant/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  owner: hill-giant
  lifecycle: experimental
